[package]
authors = ["Dimitris Lamprinos <pkakelas@gmail.com>"]
edition = "2021"
name = "types"
version = "0.1.0"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
panic = 'abort'
rpath = false

[dependencies]
alloy-primitives = "0.4.2"
alloy-rlp = {version = "0.3.3", features = ["derive", "arrayvec"]}
cosmwasm-schema = "1.1.3"
cosmwasm-std = "1.1.3"
cosmwasm-storage = "1.1.3"
cw-storage-plus = "1.0.1"
cw2 = "1.1.1"
eyre = "0.6.8"
hex = "0.4.3"
milagro_bls = {git = "https://github.com/pkakelas/milagro_bls"}
schemars = "0.8.10"
serde = {version = "1.0.145", default-features = false, features = ["derive"]}
serde_json = "1.0.105"
ssz_rs = "0.9.0"
thiserror = {version = "1.0.31"}

[dev-dependencies]
cw-multi-test = "0.16.2"
