[package]
edition = "2021"
name = "trie-verifier"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
cita_trie = "5.0.0"
cosmwasm-std = "1.4.1"
hasher = "0.1.4"
hex = "0.4.3"
serde = "1.0.189"
serde_json = "1.0.107"
thiserror = "1.0.50"

[dev-dependencies]
cw-multi-test = "0.17.0"
